gui:
  theme:
    activeBorderColor:
      - "#ae81ff"
      - bold
    inactiveBorderColor:
      - "#75715e"
    optionsTextColor:
      - "#ae81ff"
    selectedLineBgColor:
      - "#5c5a50"
    cherryPickedCommitBgColor:
      - "#5c5a50"
    cherryPickedCommitFgColor:
      - "#a6e22e"
    unstagedChangesColor:
      - "#f92672"
    defaultFgColor:
      - "#f8f8f2"
    searchingActiveBorderColor:
      - "#e6db74"
git:
  branchPrefix: "potsbo/"
keybinding:
  universal:
    prevItem-alt: t
    nextItem-alt: h
    prevBlock-alt: d
    nextBlock-alt: n
    remove: j
    new: l
