---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
checksum:
  enabled: true
  require_checksum: true
  supported_envs:
    - all
registries:
  - type: standard
    ref: v4.433.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: denoland/deno@v2.5.6
  - name: twistedpair/google-cloud-sdk@547.0.0
  - name: junegunn/fzf@v0.66.1
  - name: BurntSushi/ripgrep@15.1.0
  - name: x-motemen/ghq@v1.8.0
  - name: sharkdp/bat@v0.26.0
  - name: jqlang/jq@jq-1.8.1
  - name: direnv/direnv@v2.37.1
  - name: neovim/neovim@v0.11.5
  - name: mikefarah/yq@v4.48.1
  - name: YS-L/csvlens@v0.14.0
  - name: golang/go@go1.25.4
  - name: cli/cli@v2.83.0
  - name: Wilfred/difftastic@0.65.0
  - name: Schniz/fnm@v1.38.1
  - name: jdx/mise@v2025.11.3
  - name: git-lfs/git-lfs@v3.7.1
  - name: nodejs/node@v23.11.1
  - name: XAMPPRocky/tokei@v12.1.2
  - name: sharkdp/fd@v10.3.0
  - name: jesseduffield/lazygit@v0.56.0
  - name: go-task/task@v3.45.4
  - name: aws/aws-cli@2.31.17
  - name: astral-sh/uv@0.9.3
  - name: starship/starship@v1.24.0
  - name: zellij-org/zellij@v0.43.1
  - name: johnkerl/miller@v6.15.0
