---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
checksum:
  enabled: true
  require_checksum: true
  supported_envs:
    - all
registries:
  - type: standard
    ref: v4.464.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: denoland/deno@v2.6.0
  - name: twistedpair/google-cloud-sdk@543.0.0
  - name: junegunn/fzf@v0.67.0
  - name: BurntSushi/ripgrep@15.1.0
  - name: x-motemen/ghq@v1.8.0
  - name: sharkdp/bat@v0.26.1
  - name: jqlang/jq@jq-1.8.1
  - name: direnv/direnv@v2.37.1
  - name: neovim/neovim@v0.11.6
  - name: mikefarah/yq@v4.48.1
  - name: YS-L/csvlens@v0.15.1
  - name: golang/go@go1.25.6
  - name: cli/cli@v2.86.0
  - name: Wilfred/difftastic@0.67.0
  - name: Schniz/fnm@v1.38.1
  - name: git-lfs/git-lfs@v3.7.1
  - name: nodejs/node@v23.11.1
  - name: XAMPPRocky/tokei@v13.0.0
  - name: sharkdp/fd@v10.3.0
  - name: jesseduffield/lazygit@v0.58.1
  - name: go-task/task@v3.45.5
  - name: aws/aws-cli@2.31.17
  - name: astral-sh/uv@0.9.3
  - name: starship/starship@v1.24.1
  - name: zellij-org/zellij@v0.43.1
  - name: johnkerl/miller@v6.16.0
  - name: tldr-pages/tlrc@v1.12.0
  - name: k1LoW/git-wt@v0.16.1
  - name: k1LoW/roots@v0.4.1
  - name: joshmedeski/sesh@v2.21.0
  - name: ajeetdsouza/zoxide@v0.9.8
  - name: junegunn/fzf/fzf-tmux@v0.67.0
  - name: sxyazi/yazi@v26.1.22
  - name: github/copilot-cli@v0.0.396
  - name: anthropics/claude-code@v2.1.41
  - name: aristocratos/btop@v1.4.6
  - name: itamae-kitchen/mitamae@v1.14.4
  - name: ynqa/jnv@v0.6.1
  - name: theseus-rs/postgresql-binaries@18.1.0
