---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
checksum:
  enabled: true
  require_checksum: true
  supported_envs:
    - all
registries:
  - type: standard
    ref: v4.474.0 # renovate: depName=aquaproj/aqua-registry
packages:
  - name: denoland/deno@v2.6.0
  - name: twistedpair/google-cloud-sdk@543.0.0
  - name: junegunn/fzf@v0.68.0
  - name: BurntSushi/ripgrep@15.1.0
  - name: x-motemen/ghq@v1.9.4
  - name: sharkdp/bat@v0.26.1
  - name: jqlang/jq@jq-1.8.1
  - name: direnv/direnv@v2.37.1
  - name: neovim/neovim@v0.11.6
  - name: mikefarah/yq@v4.48.1
  - name: YS-L/csvlens@v0.15.1
  - name: golang/go@go1.26.0
  - name: cli/cli@v2.87.2
  - name: Wilfred/difftastic@0.67.0
  - name: Schniz/fnm@v1.38.1
  - name: git-lfs/git-lfs@v3.7.1
  - name: nodejs/node@v23.11.1
  - name: XAMPPRocky/tokei@v13.0.0
  - name: sharkdp/fd@v10.3.0
  - name: jesseduffield/lazygit@v0.59.0
  - name: go-task/task@v3.45.5
  - name: aws/aws-cli@2.31.17
  - name: astral-sh/uv@0.9.3
  - name: starship/starship@v1.24.1
  - name: zellij-org/zellij@v0.43.1
  - name: johnkerl/miller@v6.16.0
  - name: tldr-pages/tlrc@v1.12.0
  - name: k1LoW/git-wt@v0.24.0
  - name: k1LoW/roots@v0.4.1
  - name: joshmedeski/sesh@v2.23.0
  - name: ajeetdsouza/zoxide@v0.9.9
  - name: junegunn/fzf/fzf-tmux@v0.67.0
  - name: sxyazi/yazi@v26.1.22
  - name: github/copilot-cli@v0.0.414
  - name: anthropics/claude-code@v2.1.50
  - name: aristocratos/btop@v1.4.6
  - name: itamae-kitchen/mitamae@v1.14.4
  - name: ynqa/jnv@v0.6.2
  - name: theseus-rs/postgresql-binaries@18.2.0
  - name: bootandy/dust@v1.2.4
  - name: sachaos/viddy@v1.3.0
  - name: dev.yorhel.nl/ncdu
    version: 2.9.1
  - name: dalance/procs@v0.14.10
  - name: muesli/duf@v0.9.1
  - name: chmln/sd@v1.0.0
  - name: mr-karan/doggo@v1.1.4
  - name: orf/gping@gping-v1.20.1
  - name: fujiapple852/trippy@0.13.0
  - name: sharkdp/hexyl@v0.17.0
  - name: ducaale/xh@v0.25.3
  - name: sharkdp/hyperfine@v1.20.0
  - name: imsnif/bandwhich@v0.23.1
  - name: eza-community/eza@v0.23.4
